projectcontour/gimbal

- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
- discovery/pkg/k8s/controller.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/sync/queue.go
Fixes #51 
```
Also fix annotations on openstack discoverer deployment file.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
> discoverer: set clustername when creating syncqueue in openstack discoverer

- discovery/pkg/openstack/httplogger.go
remove punctuation of error message end
see [this](https://github.com/golang/go/wiki/CodeReviewComments#error-strings) document
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>
> discovery/pkg/openstack/httplogger.go: fix error message punctuation

- discovery/cmd/kubernetes-discoverer/main.go
discovert/cmd/kubernetes-discoverer: remove constant workingNamespace
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>
> discovert/cmd/kubernetes-discoverer: remove constant workingNamespace

- docs/README.md
- docs/teams.md
> Add team docs with sample RBAC permissions

- deployment/grafana/02-grafana-configmap.yaml
Fixes #53 
Uses kube-state-metrics to count the number of services that have been discovered by Gimbal. Specifically using the labels metrics, which we can use to count services and endpoints that have the gimbal.heptio.com/cluster label set.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
> grafana: use kube-state-metrics to count discovered svcs/endpoints

- deployment/contour/02-statsd.yaml
- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
- deployment/prometheus/02-prometheus-configmap.yaml
- docs/monitoring.md
This enables histogram support for Envoy metrics by using the [statsd exporter](https://github.com/prometheus/statsd_exporter) to collect data from Envoy and then allow Prometheus to scrape for those metrics. 
Note this PR has non-standard Contour builds as it depends on changes to enable statsd endpoints. PR for that is heptio/contour#366. Once that merges we can update the image to use a `master` tag until a new release of Contour. 
Fixes #92 
> Enable statsd metrics collection for histograms

- docs/discovery-naming-conventions.md
Initial pass at documenting discovery naming conventions and translation process. 
I wonder if we should brainstorm ways of simplifying the shortening process. Regardless, I have documented the shortening algorithm as it is implemented today.
Fixes #100 
Proposal for #71
> docs: add discovery naming conventions

- deployment/README.md
If a user follows our docs and tries to create a k8s discoverer secret with a different filename than `config`, the deployment will fail.
This PR explicitly specifies the Secret key to be `config`, regardless of which filename the kubeconfig data is in.
> [Doc] Specify the Secret key for the kubeconfig data

- deployment/grafana/02-grafana-configmap.yaml
Fixes #115 
Update the prometheus query we are using in the discovery dashboards to count the number of discovered services to use `gimbal.heptio.com/backend` instead of `gimbal.heptio.com/cluster`.
> grafana: update prometheus query to use new gimbal label

- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
Update discoverer deployment files to use `v0.2.0` tag instead of `master`.
> deployment: update discoverer images to latest released version

- deployment/prometheus/02-prometheus-configmap.yaml
The envoy-statsd scrape job should only scrape the envoy-statsd pods. Thus, only keep the pods that have the statsdport annotation.
Fixes #132
> prometheus: envoy-statsd job ignore pods that don't have the statsd port annotation

- deployment/contour/03-envoy.yaml
This sets the Envoy Daemonset to perform a rolling update when the manifest is changed. It also defines a 10% `maxUnavailable` which means it can potentially roll more than one pod at a time depending on how many total pods exist in the environment.
> Envoy daemonset does rollingUpdate when modified

- discovery/pkg/sync/queue.go
- discovery/pkg/sync/queue_test.go
Updates #134
I propose we open another issue for spec'ing a new metric that will keep track of the number of retries.
```
The client-go workqueue expects the user to mark any item that needs to
be retried as "dirty". That is, on failure, the item must be re-added to
the queue for reprocessing at a later time.
The item is added to the queue via AddRateLimited, which will add the
item once the rate limiter says it's okay.
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
> discovery: fix syncqueue retries

- discovery/pkg/openstack/diff.go
- discovery/pkg/openstack/diff_test.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/openstack/translate.go
- discovery/pkg/openstack/translate_test.go
Fixes #95 
There were two problems which have been addressed:
1. The Kubernetes API server sets the target port to the service port on creation. We were not setting the target port when translating the object, so there would always be a difference between the service that we translated and the service that exists in the gimbal cluster. The fix for this is to set the target port in the discoverer during the translation process.
2. Our diff code assumed that the slice of services/endpoints we got from the gimbal cluster were sorted in the same way as the slice of services/endpoints we got from the backend (after translation). Instead, we now perform the correct comparison by first finding the right service (or endpoint) in the slice of backend services (or endpoints), and then comparing …
> discovery/openstack: set TargetPort and ignore sort order for update detection

- discovery/cmd/kubernetes-discoverer/main.go
- discovery/cmd/openstack-discoverer/main.go
- discovery/pkg/k8s/client.go
- docs/README.md
- docs/kubernetes-discoverer.md
- docs/openstack-discoverer.md
Fixes #150 
This PR makes the client request rate limits against the Gimbal kubernetes API server configurable via command-line flags on both the kubernetes and openstack discoverers.
New flags:
| flag  | default  | description  |
|---|---|---|
| `--gimbal-client-qps` | 5 | The maximum queries per second (QPS) that can be performed on the Gimbal Kubernetes API server
| `--gimbal-client-burst` | 10 | The maximum number of queries that can be performed on the Gimbal Kubernetes API server during a burst
I decided to go with the client-go defaults, which means that the user will most likely always want to set these flags when deploying Gimbal.
With that said, it might be worth setting defaults that are higher, but I am not sure what those would be. I am also interested in feedback on the …
> discovery: make gimbal client request rate limit configurable

- .gitignore
- discovery/cmd/kubernetes-discoverer/main.go
- discovery/cmd/openstack-discoverer/main.go
- discovery/pkg/k8s/controller.go
- discovery/pkg/k8s/controller_test.go
- discovery/pkg/metrics/metrics.go
- discovery/pkg/openstack/diff.go
- discovery/pkg/openstack/diff_test.go
- discovery/pkg/openstack/httplogger.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/openstack/translate.go
- discovery/pkg/openstack/translate_test.go
- discovery/pkg/sync/endpoints.go
- discovery/pkg/sync/endpoints_test.go
- discovery/pkg/sync/queue.go
- discovery/pkg/sync/queue_test.go
- discovery/pkg/sync/service.go
- discovery/pkg/sync/service_test.go
- discovery/pkg/sync/time.go
- docs/monitoring.md
Add additional metrics to the Discoverers:
- upstream-services
- replicated-services
-  invalid-services
- upstream-endpoints
- replicated-endpoints
- invalid-endpoints
// Fixes #108 
> Additional metrics 

- deployment/README.md
> deployment: remove kube-state-metrics from docs

- discovery/cmd/openstack-discoverer/main.go
I *think* this was added when we were thinking of using an informer for stats. We ended up taking another route, but the flag was left behind.
Fixes #153
> discovery/openstack: remove unused 'resync-interval' flag

- discovery/pkg/k8s/controller.go
- discovery/pkg/k8s/controller_test.go
- docs/monitoring.md
Fixes #155 
```
The kubernetes service is ignored by the discoverer when replicating
services into the gimbal cluster. Thus, the upstream service count
metric should not include the kubernetes service.
```
> discovery: do not count the default kubernetes svc as an upstream svc

- docs/monitoring.md
Add sample alert rules to the alert manager documentation.
Open to suggestions on other (or alternative) alerts that might make sense to showcase.
> docs/monitoring: add sample alert rules

- discovery/pkg/sync/queue.go
- discovery/pkg/sync/queue_test.go
With this change, the metrics are only set when we have successfully handled an item. Otherwise, the metrics could be misleading. For example, if we fail to sync an endpoints object, we would still increment the `gimbal_discoverer_replicated_endpoints_total` metric, even though the endpoints object was not replicated.
The downside, which I am still unsure whether it is a problem or not, is that the timestamp metric will only be updated when the item is processed successfully.
Fixes #154
> pkg/sync: only set success metrics when item is processed successfully

- deployment/grafana/02-grafana-configmap.yaml
- discovery/pkg/metrics/metrics.go
- docs/monitoring.md
Fixes #163 
- Changed the API latency and OpenStack cycle time metrics to use a histogram instead of a gauge. 
- Updated the dashboards to display 50th,75th, 90th, and 100th percentiles.
- Updated metrics documentation
I suspect we'll have to make the bucket sizes configurable, but I think we can follow up on that when time comes.
> monitoring: use histograms for api latency and cycle time metrics

- deployment/README.md
* Grafana no longer needs to be configured to talk to prometheus
* Grafana dashboards are pre-configured
* Change doc label selector to pickup all backends
> Minor cleanup of deployment docs

- discovery/pkg/k8s/translate.go
- discovery/pkg/k8s/translate_test.go
When discovering services and endpoints, include the annotations as well.
Fixes #178
> discovery: set annotation on discovered services and endpoints

- deployment/contour/02-rbac.yaml
Contour RBAC policies for IngressRoute CRD were updated to include the ability to update the status field.
> Update contour RBAC to support writing status

- README.md
- docs/README.md
- docs/route.md
- docs/teams.md
> Docs refresh for Contour 0.6-beta.1. Fixes #171

- deployment/contour/03-contour.yaml
- deployment/grafana/02-grafana-configmap.yaml
- Adds new Grafana dashboard to visualize Root, Total, Invalid, Valid, & Orphaned IngressRoute metrics. 
- Move the CDS / LDS updates to new dashboard from Envoy metrics dashboard
- Update Contour deployment to add Prometheus annotations to have it be scraped for metrics
- Update Contour deployment to expose `debug` endpoint which allows Prometheus to scrape
NOTE: This needs a build from Contour that is not a released version. You can use the image `stevesloka/contour:metrics` to test.
Fixes #174 
> Update Contour to be scraped for metrics / Add Contour dashboard

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Update to contour v0.6.0-beta.2. Fixes #185

- deployment/contour/03-contour.yaml
Once (https://github.com/heptio/contour/pull/593) lands the /metrics port will be exposed directly without needing to expose the debug ports. This PR updates the deployment to remove the debug interface. 
> Remove debug listener from Deployment

- deployment/grafana/02-grafana-configmap.yaml
Update the replicated services by backend panel to use sum() instead of avg()
Fixes #191
> deployment/grafana: sum the replicated services by backend

- deployment/grafana/02-grafana-configmap.yaml
Fixes #190 by adding missing P99 to the Downstream Latency panel. The previous PR added to Upstream. 
> Add P99 latency to Downstream Latency panel

- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
- discovery/cmd/openstack-discoverer/main.go
I tried to deploy OpenStack Discoverer, but failed to start it cause of conflict between Prometheus port and LivenessProve port. Error messages are below.
```
time="2018-08-22T02:48:33Z" level=info msg="Gimbal OpenStack Discoverer Starting up..."
time="2018-08-22T02:48:33Z" level=info msg="Version: v0.3.0-beta.3"
time="2018-08-22T02:48:33Z" level=info msg="Backend name: os01"
time="2018-08-22T02:48:33Z" level=info msg="Number of queue worker threads: 2"
time="2018-08-22T02:48:33Z" level=info msg="Reconciliation period: 30s"
time="2018-08-22T02:48:33Z" level=info msg="Gimbal kubernetes client QPS: 5"
time="2018-08-22T02:48:33Z" level=info msg="Gimbal kubernetes client burst: 10"
time="2018-08-22T02:48:33Z" level=info msg="BackendName is: os01"
time="2018-08-22T02:48:33Z" level=info …
```
> Change OpenStack Discoverer listen port for LivenessProve

- discovery/cmd/openstack-discoverer/main.go
Fixes #207 by allowing the openstack client to automatically refresh the auth token. Also, if the auth fails more the 3 times, then the app will quit and be restarted. 
> Add flag to have openstack client re-auth when token expires

- discovery/pkg/openstack/translate.go
- discovery/pkg/openstack/translate_test.go
- docs/discovery-naming-conventions.md
Updates the openstack translation process to only use the load balancer's ID as the service/endpoint name. The load balancer name is still available as a label on the service.
Fixes #216
> discovery: don't make lb name part of the k8s name

- discovery/pkg/openstack/reconciler.go
Fixes #230 
Fixes the reconciler by taking the pointer of an intermediate var instead of the range var.
> pkg/openstack: enqueue the actual svcs instead of a ptr to the range var

- README.md
Hi,
I added Travis CI build badge on README.md in order to check the health of the code easily.
> Add a build badge on README.md

- discovery/cmd/openstack-discoverer/main.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/openstack/reconciler_test.go
- docs/openstack-discoverer.md
I tried to deploy OpenStack Discoverer, but sync cycle was too long on a OpenStack cluster which has many projects.
My suggestion is to implement whitelist for rapid sync cycle.
```
$ kubectl logs openstack-discoverer-5556b6dcbc-ptj6n -n gimbal-discovery | grep 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'
time="2018-10-28T22:20:33Z" level=info msg="Successfully handled: update service 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T22:51:58Z" level=info msg="Successfully handled: update endpoints 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T22:51:59Z" level=info msg="Successfully handled: update service 'dreco-001/openstack-626c5bf1-3cf8-438a-b6a1-e20419126eee'"
time="2018-10-28T23:23:19Z" level=info …
```
> Add whitelist to limit openstack loadbalancers

- .travis.yml
- discovery/Dockerfile
- discovery/Makefile
- discovery/hack/build.sh
- discovery/hack/test.sh
- discovery/hack/verify-all.sh
- discovery/hack/verify-fmt.sh
- discovery/pkg/sync/queue_test.go
- discovery/pkg/translator/translator_test.go
Fixes #259 by removing alpine and switching to debian-slim. Also, fixes build scripts for go1.12
Signed-off-by: Steve Sloka <steve@stevesloka.com>
> Remove alpine from base images & build images. 

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
Fixes #144 by adding a preStop hook as well as a readiness probe to Envoy.
> Add prestop hook & readiness probe to Envoy

- .travis.yml
- Dockerfile
- README.md
- SUPPORT.md
- cmd/kubernetes-discoverer/main.go
- cmd/openstack-discoverer/main.go
- deployment/README.md
- docs/route.md
- go.mod
- pkg/k8s/controller.go
- pkg/k8s/controller_test.go
- pkg/k8s/translate.go
- pkg/openstack/httplogger.go
- pkg/openstack/reconciler.go
- pkg/openstack/translate.go
- pkg/sync/endpoints.go
- pkg/sync/endpoints_test.go
- pkg/sync/queue.go
- pkg/sync/queue_test.go
- pkg/sync/service.go
- pkg/sync/service_test.go
This updates the code base from the Github org move from `vmware-tanzu` --> `projectcontour`. 
> Rename vmware-tanzu --> projectcontour

- deployment/README.md
- design/kubernetes.md
- docs/discovery-naming-conventions.md
- docs/kubernetes-discoverer.md
- docs/list-discovered-services.md
- docs/manage-backends.md
- docs/openstack-discoverer.md
- pkg/k8s/controller_test.go
- pkg/k8s/translate_test.go
- pkg/openstack/translate.go
- pkg/openstack/translate_test.go
- pkg/sync/endpoints_test.go
- pkg/sync/service.go
- pkg/sync/service_test.go
- pkg/translator/translator.go
- pkg/translator/translator_test.go
Fixes #280 by renaming the `gimbal.heptio.com` labels to `gimbal.projectcontour.io`. 
> Rename gimbal labels to 'gimbal.projectcontour.io'
