- deployment/contour/02-deployment.yaml
> Bump contour version to v0.5.0

- discovery/pkg/sync/endpoints.go
- discovery/pkg/sync/service.go
> discovery/pkg/sync: use single-quotes in log messages

- discovery/cmd/kubernetes-discoverer/main.go
- discovery/cmd/openstack-discoverer/main.go
- docs/openstack-discoverer.md
> discovery: make the openstack user domain name configurable

- deployment/README.md
Fixes/updates table of contents in deployment readme.
> deployment/readme: fix TOC links

- discovery/pkg/openstack/client.go
typo fixed
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>
> discovery/pkg/openstack/client.go: fix typo

- discovery/pkg/openstack/translate.go
```
Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```
> discovery/pkg/openstack: remove unused constant

- deployment/grafana/02-grafana-configmap.yaml
- discovery/pkg/metrics/metrics.go
- discovery/pkg/sync/queue.go
- docs/monitoring.md
> Add Queue Size / Openstack API Latency / Openstack Cycle time metrics

- discovery/pkg/util/util.go
Improve performance by precompiling regex and additional thread-safe implementation
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>
> Improve performance by precompiling regex

- deployment/README.md
> Docs on stateful Prometheus deployment

- deployment/contour/01-common.yaml
- deployment/contour/02-rbac.yaml
- deployment/contour/03-envoy.yaml
> Update stats port for prometheus metrics / Add IngressRoute CRD

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Link to Contour tag v0.6.0-alpha.1

- deployment/README.md
- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
- deployment/grafana/02-grafana-configmap.yaml
- discovery/README.md
- discovery/cmd/kubernetes-discoverer/main.go
- discovery/cmd/openstack-discoverer/main.go
- discovery/design/kubernetes.md
- discovery/design/openstack.md
- discovery/pkg/k8s/controller.go
- discovery/pkg/k8s/controller_test.go
- discovery/pkg/k8s/translate.go
- discovery/pkg/k8s/translate_test.go
- discovery/pkg/metrics/metrics.go
- discovery/pkg/openstack/httplogger.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/openstack/translate.go
- discovery/pkg/openstack/translate_test.go
- discovery/pkg/sync/endpoints.go
- discovery/pkg/sync/queue.go
- discovery/pkg/sync/service.go
- discovery/pkg/translator/translator.go
- discovery/pkg/translator/translator_test.go
- discovery/pkg/util/util.go
- discovery/pkg/util/util_test.go
- docs/discovery-naming-conventions.md
- docs/kubernetes-discoverer.md
- docs/manage-backends.md
- docs/monitoring.md
- docs/openstack-discoverer.md
> Rename cluster-name to backend-name

- README.md
- deployment/README.md
- discovery/README.md
- docs/discovery-naming-conventions.md
- docs/list-discovered-services.md
- docs/manage-backends.md
- docs/monitoring.md
- docs/teams.md
Signed-off-by: JENNIFER RONDEAU <jrondeau@heptio.com>
Copyedits:
- moving toward standardized/corrected capitalization for product names, consistency, matching upstream practice (WIP)
- future tense -> present tense
- reducing duplicate content. More work to be done here.
- clarifying a few points.
> edit docs for 0.2 release

- .gitignore
- deployment/grafana/02-grafana-configmap.yaml
- discovery/cmd/kubernetes-discoverer/main.go
- discovery/cmd/openstack-discoverer/main.go
- discovery/pkg/k8s/client.go
- discovery/pkg/k8s/controller.go
- discovery/pkg/k8s/controller_test.go
- discovery/pkg/metrics/metrics.go
- discovery/pkg/openstack/diff.go
- discovery/pkg/openstack/diff_test.go
- discovery/pkg/openstack/httplogger.go
- discovery/pkg/openstack/reconciler.go
- discovery/pkg/openstack/translate.go
- discovery/pkg/openstack/translate_test.go
- discovery/pkg/sync/endpoints.go
- discovery/pkg/sync/endpoints_test.go
- discovery/pkg/sync/queue.go
- discovery/pkg/sync/queue_test.go
- discovery/pkg/sync/service.go
- discovery/pkg/sync/service_test.go
- discovery/pkg/sync/time.go
- docs/README.md
- docs/kubernetes-discoverer.md
- docs/monitoring.md
- docs/openstack-discoverer.md
Work in progress, don't merge until after #143 is completed.
> Updated Grafana Discovery dashboard using new discoverer metrics

- deployment/contour/01-common.yaml
> Add ingress route crd validation from Contour

- deployment/contour/01-common.yaml
- deployment/contour/03-contour.yaml
Fixes #165 by updating extensions/v1beta1 deployment type to apps/v1. Also, pull in updated CRD validation from Contour.
> Update Contour deployment type & update crd validation

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Update Gimbal to use Contour 0.6-beta.1

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> deployment/contour: bump contour version to v0.6.0-beta.3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_enhancement_request.md
Signed-off-by: Kris Dockery <kris@heptio.com>
> Add bug/rfe templates

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
Revert contour image to latest released version.
> deployment/contour: revert to contour:v0.6.0-beta.2

- deployment/grafana/02-grafana-configmap.yaml
> Fixes #211. Update templated variables to use regex All value

- deployment/grafana/02-grafana-configmap.yaml
> Fixes #214. Add endpoint health data to Envoy dashboard

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Update Contour to beta-3

- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
> Fix location of probe from k8s discoverer to openstack

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
> Update Contour version to v0.6.0 and Discoverer to v0.3.0

- deployment/contour/03-envoy.yaml
Update dns policy for pods running with hostNetwork: true
// ref: https://github.com/heptio/contour/issues/686
Signed-off-by: Steve Sloka <steve@stevesloka.com>
> Update the dns policy

- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
> Bump discoverer versions to v0.3.1

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Update to Contour v0.7.0 and Envoy v1.7.0

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
> Bump Contour version to v0.8.0 and Gimbal to v0.4.0

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
Fixes #252 by updating the Contour & Envoy version.
> Update Contour to v0.9.0 and Envoy to v1.9.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- deployment/README.md
- discovery/Dockerfile
> Update Heptio branding

- deployment/contour/03-contour.yaml
> Updates contour to v0.10.0

- deployment/contour/03-contour.yaml
- deployment/contour/03-envoy.yaml
> Bump version to Contour v0.11.0 & Envoy v1.9.1

- deployment/contour/01-common.yaml
- deployment/contour/02-rbac.yaml
- deployment/contour/03-contour.yaml
fixes #263 
Signed-off-by: Peter Grant <9246508+pickledrick@users.noreply.github.com>
> fix missed merge contour deployment manifest

- docs/teams.md
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>
> Fixed a small spelling error in docs/teams.md

- Dockerfile
> Update dockerfile with latest golang version / Fix location of binaries

- deployment/gimbal-discoverer/02-kubernetes-discoverer.yaml
- deployment/gimbal-discoverer/02-openstack-discoverer.yaml
> deployment: Move discoverer deployments to apps/v1
